//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/27/2013 10:33:01 AM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationDataObjectContext in the schema.
    /// </summary>
    public partial class ApplicationDataObjectContext : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationDataObjectContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LightSwitchApplication", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LightSwitchApplication.Implementation", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Subscriber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SubscriberItem> Subscriber
        {
            get
            {
                if ((this._Subscriber == null))
                {
                    this._Subscriber = base.CreateQuery<SubscriberItem>("Subscriber");
                }
                return this._Subscriber;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SubscriberItem> _Subscriber;
        /// <summary>
        /// There are no comments for Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PhoneItem> Phone
        {
            get
            {
                if ((this._Phone == null))
                {
                    this._Phone = base.CreateQuery<PhoneItem>("Phone");
                }
                return this._Phone;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PhoneItem> _Phone;
        /// <summary>
        /// There are no comments for ServicePlans in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ServicePlan> ServicePlans
        {
            get
            {
                if ((this._ServicePlans == null))
                {
                    this._ServicePlans = base.CreateQuery<ServicePlan>("ServicePlans");
                }
                return this._ServicePlans;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ServicePlan> _ServicePlans;
        /// <summary>
        /// There are no comments for Subscriber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSubscriber(SubscriberItem subscriberItem)
        {
            base.AddObject("Subscriber", subscriberItem);
        }
        /// <summary>
        /// There are no comments for Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPhone(PhoneItem phoneItem)
        {
            base.AddObject("Phone", phoneItem);
        }
        /// <summary>
        /// There are no comments for ServicePlans in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToServicePlans(ServicePlan servicePlan)
        {
            base.AddObject("ServicePlans", servicePlan);
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.SubscriberItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Subscriber")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SubscriberItem : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SubscriberItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SubscriberItem CreateSubscriberItem(int ID, byte[] rowVersion, string firstName, string lastName)
        {
            SubscriberItem subscriberItem = new SubscriberItem();
            subscriberItem.Id = ID;
            subscriberItem.RowVersion = rowVersion;
            subscriberItem.FirstName = firstName;
            subscriberItem.LastName = lastName;
            return subscriberItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                if (object.Equals(this.FirstName, value))
                {
                    return;
                }
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                if (object.Equals(this.LastName, value))
                {
                    return;
                }
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                if (object.Equals(this.Comment, value))
                {
                    return;
                }
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property GroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GroupId
        {
            get
            {
                return this._GroupId;
            }
            set
            {
                this.OnGroupIdChanging(value);
                if (object.Equals(this.GroupId, value))
                {
                    return;
                }
                this._GroupId = value;
                this.OnGroupIdChanged();
                this.OnPropertyChanged("GroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GroupId;
        partial void OnGroupIdChanging(string value);
        partial void OnGroupIdChanged();
        /// <summary>
        /// There are no comments for Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PhoneItem> Phone
        {
            get
            {
                this.@__Phone.EnsureValueInitialized();
                return this._Phone;
            }
            set
            {
                this._Phone = value;
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PhoneItem> _Phone = new global::System.Data.Services.Client.DataServiceCollection<PhoneItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.PhoneItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Phone")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PhoneItem : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PhoneItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="mDN">Initial value of MDN.</param>
        /// <param name="mSID">Initial value of MSID.</param>
        /// <param name="mEID">Initial value of MEID.</param>
        /// <param name="eSN">Initial value of ESN.</param>
        /// <param name="mSL">Initial value of MSL.</param>
        /// <param name="active">Initial value of Active.</param>
        /// <param name="phoneItem_SubscriberItem">Initial value of PhoneItem_SubscriberItem.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PhoneItem CreatePhoneItem(int ID, byte[] rowVersion, string mDN, string mSID, string mEID, string eSN, string mSL, bool active, int phoneItem_SubscriberItem)
        {
            PhoneItem phoneItem = new PhoneItem();
            phoneItem.Id = ID;
            phoneItem.RowVersion = rowVersion;
            phoneItem.MDN = mDN;
            phoneItem.MSID = mSID;
            phoneItem.MEID = mEID;
            phoneItem.ESN = eSN;
            phoneItem.MSL = mSL;
            phoneItem.Active = active;
            phoneItem.PhoneItem_SubscriberItem = phoneItem_SubscriberItem;
            return phoneItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property MDN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MDN
        {
            get
            {
                return this._MDN;
            }
            set
            {
                this.OnMDNChanging(value);
                if (object.Equals(this.MDN, value))
                {
                    return;
                }
                this._MDN = value;
                this.OnMDNChanged();
                this.OnPropertyChanged("MDN");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MDN;
        partial void OnMDNChanging(string value);
        partial void OnMDNChanged();
        /// <summary>
        /// There are no comments for Property MSID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MSID
        {
            get
            {
                return this._MSID;
            }
            set
            {
                this.OnMSIDChanging(value);
                if (object.Equals(this.MSID, value))
                {
                    return;
                }
                this._MSID = value;
                this.OnMSIDChanged();
                this.OnPropertyChanged("MSID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MSID;
        partial void OnMSIDChanging(string value);
        partial void OnMSIDChanged();
        /// <summary>
        /// There are no comments for Property MEID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MEID
        {
            get
            {
                return this._MEID;
            }
            set
            {
                this.OnMEIDChanging(value);
                if (object.Equals(this.MEID, value))
                {
                    return;
                }
                this._MEID = value;
                this.OnMEIDChanged();
                this.OnPropertyChanged("MEID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MEID;
        partial void OnMEIDChanging(string value);
        partial void OnMEIDChanged();
        /// <summary>
        /// There are no comments for Property ESN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ESN
        {
            get
            {
                return this._ESN;
            }
            set
            {
                this.OnESNChanging(value);
                if (object.Equals(this.ESN, value))
                {
                    return;
                }
                this._ESN = value;
                this.OnESNChanged();
                this.OnPropertyChanged("ESN");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ESN;
        partial void OnESNChanging(string value);
        partial void OnESNChanged();
        /// <summary>
        /// There are no comments for Property MSL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MSL
        {
            get
            {
                return this._MSL;
            }
            set
            {
                this.OnMSLChanging(value);
                if (object.Equals(this.MSL, value))
                {
                    return;
                }
                this._MSL = value;
                this.OnMSLChanged();
                this.OnPropertyChanged("MSL");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MSL;
        partial void OnMSLChanging(string value);
        partial void OnMSLChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                if (object.Equals(this.Active, value))
                {
                    return;
                }
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property DeviceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeviceType
        {
            get
            {
                return this._DeviceType;
            }
            set
            {
                this.OnDeviceTypeChanging(value);
                if (object.Equals(this.DeviceType, value))
                {
                    return;
                }
                this._DeviceType = value;
                this.OnDeviceTypeChanged();
                this.OnPropertyChanged("DeviceType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeviceType;
        partial void OnDeviceTypeChanging(string value);
        partial void OnDeviceTypeChanged();
        /// <summary>
        /// There are no comments for Property Manufacturer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Manufacturer
        {
            get
            {
                return this._Manufacturer;
            }
            set
            {
                this.OnManufacturerChanging(value);
                if (object.Equals(this.Manufacturer, value))
                {
                    return;
                }
                this._Manufacturer = value;
                this.OnManufacturerChanged();
                this.OnPropertyChanged("Manufacturer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Manufacturer;
        partial void OnManufacturerChanging(string value);
        partial void OnManufacturerChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                if (object.Equals(this.Comment, value))
                {
                    return;
                }
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property PhoneType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneType
        {
            get
            {
                return this._PhoneType;
            }
            set
            {
                this.OnPhoneTypeChanging(value);
                if (object.Equals(this.PhoneType, value))
                {
                    return;
                }
                this._PhoneType = value;
                this.OnPhoneTypeChanged();
                this.OnPropertyChanged("PhoneType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneType;
        partial void OnPhoneTypeChanging(string value);
        partial void OnPhoneTypeChanged();
        /// <summary>
        /// There are no comments for Property PhoneItem_SubscriberItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PhoneItem_SubscriberItem
        {
            get
            {
                return this._PhoneItem_SubscriberItem;
            }
            set
            {
                this.OnPhoneItem_SubscriberItemChanging(value);
                if (object.Equals(this.PhoneItem_SubscriberItem, value))
                {
                    return;
                }
                this._PhoneItem_SubscriberItem = value;
                this.OnPhoneItem_SubscriberItemChanged();
                this.OnPropertyChanged("PhoneItem_SubscriberItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PhoneItem_SubscriberItem;
        partial void OnPhoneItem_SubscriberItemChanging(int value);
        partial void OnPhoneItem_SubscriberItemChanged();
        /// <summary>
        /// There are no comments for SubscriberItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SubscriberItem SubscriberItem
        {
            get
            {
                this.@__SubscriberItem.EnsureValueInitialized();
                return this._SubscriberItem;
            }
            set
            {
                SubscriberItem previous = this.SubscriberItem;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._SubscriberItem = null;
                    this.@__SubscriberItem.OnValueSet();
                    previous.Phone.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.PhoneItem_SubscriberItem = value.Id;
                    }
                    else
                    {
                        this.PhoneItem_SubscriberItem = default(int);
                    }
                }
                this._SubscriberItem = value;
                this.@__SubscriberItem.OnValueSet();
                if ((value != null))
                {
                    value.@__Phone.Add(this);
                }
                this.___OnPropertyChanged("SubscriberItem");
                this.OnPropertyChanged("SubscriberItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SubscriberItem _SubscriberItem;
        /// <summary>
        /// There are no comments for ServicePlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ServicePlan ServicePlan
        {
            get
            {
                this.@__ServicePlan.EnsureValueInitialized();
                return this._ServicePlan;
            }
            set
            {
                ServicePlan previous = this.ServicePlan;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._ServicePlan = null;
                    this.@__ServicePlan.OnValueSet();
                    previous.PhoneItem = null;
                }
                this._ServicePlan = value;
                this.@__ServicePlan.OnValueSet();
                if ((value != null))
                {
                    value.PhoneItem = this;
                }
                this.___OnPropertyChanged("ServicePlan");
                this.OnPropertyChanged("ServicePlan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ServicePlan _ServicePlan;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.ServicePlan in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ServicePlans")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ServicePlan : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ServicePlan object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="internationalDialing">Initial value of InternationalDialing.</param>
        /// <param name="voicePlan">Initial value of VoicePlan.</param>
        /// <param name="dataPlan">Initial value of DataPlan.</param>
        /// <param name="hotSpot">Initial value of HotSpot.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ServicePlan CreateServicePlan(int ID, byte[] rowVersion, bool internationalDialing, string voicePlan, string dataPlan, bool hotSpot)
        {
            ServicePlan servicePlan = new ServicePlan();
            servicePlan.Id = ID;
            servicePlan.RowVersion = rowVersion;
            servicePlan.InternationalDialing = internationalDialing;
            servicePlan.VoicePlan = voicePlan;
            servicePlan.DataPlan = dataPlan;
            servicePlan.HotSpot = hotSpot;
            return servicePlan;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property InternationalDialing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool InternationalDialing
        {
            get
            {
                return this._InternationalDialing;
            }
            set
            {
                this.OnInternationalDialingChanging(value);
                if (object.Equals(this.InternationalDialing, value))
                {
                    return;
                }
                this._InternationalDialing = value;
                this.OnInternationalDialingChanged();
                this.OnPropertyChanged("InternationalDialing");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _InternationalDialing;
        partial void OnInternationalDialingChanging(bool value);
        partial void OnInternationalDialingChanged();
        /// <summary>
        /// There are no comments for Property VoicePlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VoicePlan
        {
            get
            {
                return this._VoicePlan;
            }
            set
            {
                this.OnVoicePlanChanging(value);
                if (object.Equals(this.VoicePlan, value))
                {
                    return;
                }
                this._VoicePlan = value;
                this.OnVoicePlanChanged();
                this.OnPropertyChanged("VoicePlan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VoicePlan;
        partial void OnVoicePlanChanging(string value);
        partial void OnVoicePlanChanged();
        /// <summary>
        /// There are no comments for Property DataPlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DataPlan
        {
            get
            {
                return this._DataPlan;
            }
            set
            {
                this.OnDataPlanChanging(value);
                if (object.Equals(this.DataPlan, value))
                {
                    return;
                }
                this._DataPlan = value;
                this.OnDataPlanChanged();
                this.OnPropertyChanged("DataPlan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DataPlan;
        partial void OnDataPlanChanging(string value);
        partial void OnDataPlanChanged();
        /// <summary>
        /// There are no comments for Property HotSpot in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool HotSpot
        {
            get
            {
                return this._HotSpot;
            }
            set
            {
                this.OnHotSpotChanging(value);
                if (object.Equals(this.HotSpot, value))
                {
                    return;
                }
                this._HotSpot = value;
                this.OnHotSpotChanged();
                this.OnPropertyChanged("HotSpot");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _HotSpot;
        partial void OnHotSpotChanging(bool value);
        partial void OnHotSpotChanged();
        /// <summary>
        /// There are no comments for PhoneItem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PhoneItem PhoneItem
        {
            get
            {
                this.@__PhoneItem.EnsureValueInitialized();
                return this._PhoneItem;
            }
            set
            {
                PhoneItem previous = this.PhoneItem;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._PhoneItem = null;
                    this.@__PhoneItem.OnValueSet();
                    previous.ServicePlan = null;
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Id = value.Id;
                    }
                    else
                    {
                        this.Id = default(int);
                    }
                }
                this._PhoneItem = value;
                this.@__PhoneItem.OnValueSet();
                if ((value != null))
                {
                    value.ServicePlan = this;
                }
                this.___OnPropertyChanged("PhoneItem");
                this.OnPropertyChanged("PhoneItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PhoneItem _PhoneItem;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
