//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region SubscriberItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SubscriberItem :
        global::LightSwitchApplication.SubscriberItem.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnCommentChanged()
        {
            this.___OnPropertyChanged("Comment");
        }
        
        partial void OnGroupIdChanged()
        {
            this.___OnPropertyChanged("GroupId");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SubscriberItem.DetailsClass.IImplementation.Phone
        {
            get
            {
                return this.Phone;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PhoneItem> __Phone
        {
            get
            {
                if (this.___Phone == null)
                {
                    this.___Phone = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PhoneItem>(
                        this,
                        "Phone",
                        () => this._Phone,
                        e => global::System.Object.Equals(e.PhoneItem_SubscriberItem, this.Id));
                }
                return this.___Phone;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PhoneItem> ___Phone;
        
    }
    #endregion
    
    #region PhoneItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PhoneItem :
        global::LightSwitchApplication.PhoneItem.DetailsClass.IImplementation
    {
        partial void OnPhoneItem_SubscriberItemChanged()
        {
            this.___OnPropertyChanged("PhoneItem_SubscriberItem");
            this.___OnPropertyChanged("SubscriberItem");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnMDNChanged()
        {
            this.___OnPropertyChanged("MDN");
        }
        
        partial void OnMSIDChanged()
        {
            this.___OnPropertyChanged("MSID");
        }
        
        partial void OnMEIDChanged()
        {
            this.___OnPropertyChanged("MEID");
        }
        
        partial void OnESNChanged()
        {
            this.___OnPropertyChanged("ESN");
        }
        
        partial void OnMSLChanged()
        {
            this.___OnPropertyChanged("MSL");
        }
        
        partial void OnActiveChanged()
        {
            this.___OnPropertyChanged("Active");
        }
        
        partial void OnDeviceTypeChanged()
        {
            this.___OnPropertyChanged("DeviceType");
        }
        
        partial void OnManufacturerChanged()
        {
            this.___OnPropertyChanged("Manufacturer");
        }
        
        partial void OnCommentChanged()
        {
            this.___OnPropertyChanged("Comment");
        }
        
        partial void OnPhoneTypeChanged()
        {
            this.___OnPropertyChanged("PhoneType");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PhoneItem.DetailsClass.IImplementation.SubscriberItem
        {
            get
            {
                return this.SubscriberItem;
            }
            set
            {
                this.SubscriberItem = (global::LightSwitchApplication.Implementation.SubscriberItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SubscriberItem> __SubscriberItem
        {
            get
            {
                if (this.___SubscriberItem == null)
                {
                    this.___SubscriberItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SubscriberItem>(
                        this,
                        "SubscriberItem",
                        new string[] { "PhoneItem_SubscriberItem" },
                        e => global::System.Object.Equals(e.Id, this.PhoneItem_SubscriberItem),
                        () => this._SubscriberItem,
                        e => this._SubscriberItem = e);
                }
                return this.___SubscriberItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SubscriberItem> ___SubscriberItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PhoneItem.DetailsClass.IImplementation.ServicePlan
        {
            get
            {
                return this.ServicePlan;
            }
            set
            {
                this.ServicePlan = (global::LightSwitchApplication.Implementation.ServicePlan)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServicePlan> __ServicePlan
        {
            get
            {
                if (this.___ServicePlan == null)
                {
                    this.___ServicePlan = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServicePlan>(
                        this,
                        "ServicePlan",
                        new string[] { "Id" },
                        e => global::System.Object.Equals(e.Id, this.Id),
                        () => this._ServicePlan,
                        e => this._ServicePlan = e);
                }
                return this.___ServicePlan;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServicePlan> ___ServicePlan;
        
    }
    #endregion
    
    #region ServicePlan
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ServicePlan :
        global::LightSwitchApplication.ServicePlan.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
            this.___OnPropertyChanged("PhoneItem");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnInternationalDialingChanged()
        {
            this.___OnPropertyChanged("InternationalDialing");
        }
        
        partial void OnVoicePlanChanged()
        {
            this.___OnPropertyChanged("VoicePlan");
        }
        
        partial void OnDataPlanChanged()
        {
            this.___OnPropertyChanged("DataPlan");
        }
        
        partial void OnHotSpotChanged()
        {
            this.___OnPropertyChanged("HotSpot");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ServicePlan.DetailsClass.IImplementation.PhoneItem
        {
            get
            {
                return this.PhoneItem;
            }
            set
            {
                this.PhoneItem = (global::LightSwitchApplication.Implementation.PhoneItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PhoneItem> __PhoneItem
        {
            get
            {
                if (this.___PhoneItem == null)
                {
                    this.___PhoneItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PhoneItem>(
                        this,
                        "PhoneItem",
                        new string[] { "Id" },
                        e => global::System.Object.Equals(e.Id, this.Id),
                        () => this._PhoneItem,
                        e => this._PhoneItem = e);
                }
                return this.___PhoneItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PhoneItem> ___PhoneItem;
        
    }
    #endregion
    
    #region ApplicationDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.SubscriberItem))
            {
                return new global::LightSwitchApplication.Implementation.SubscriberItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PhoneItem))
            {
                return new global::LightSwitchApplication.Implementation.PhoneItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ServicePlan))
            {
                return new global::LightSwitchApplication.Implementation.ServicePlan();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.SubscriberItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SubscriberItem);
            }
            if (typeof(global::LightSwitchApplication.PhoneItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PhoneItem);
            }
            if (typeof(global::LightSwitchApplication.ServicePlan) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ServicePlan);
            }
            return null;
        }
    }
}
