//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SuscriberSearch
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SuscriberSearch() : base("LightSwitchApplication:SuscriberSearch")
        {
            global::LightSwitchApplication.SuscriberSearch.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SuscriberSearch CreateInstance()
        {
            return new global::LightSwitchApplication.SuscriberSearch(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SuscriberSearch_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SuscriberSearch_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SuscriberSearch_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SuscriberSearch_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SuscriberSearch_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SuscriberSearch_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SuscriberSearch_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Query1_SelectionChanged();

        partial void Query1_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query1_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Query1 visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.SubscriberItem> Query1
        {
            get
            {
                return global::LightSwitchApplication.SuscriberSearch.DetailsClass.GetValue(this, global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties.Query1);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query1_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySet, global::LightSwitchApplication.SuscriberSearch.DetailsClass.CommandSet, global::LightSwitchApplication.SuscriberSearch.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties.Query1;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass>.Entry
                __SuscriberSearchEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass>.Entry(
                    global::LightSwitchApplication.SuscriberSearch.DetailsClass.__SuscriberSearch_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SuscriberSearch.DetailsClass.__SuscriberSearch_InvokeSavingEvent,
                    global::LightSwitchApplication.SuscriberSearch.DetailsClass.__SuscriberSearch_InvokeSavedEvent,
                    global::LightSwitchApplication.SuscriberSearch.DetailsClass.__SuscriberSearch_InvokeClosingEvent,
                    global::LightSwitchApplication.SuscriberSearch.DetailsClass.__SuscriberSearch_InvokeCreated,
                    global::LightSwitchApplication.SuscriberSearch.DetailsClass.__SuscriberSearch_InvokeActivated,
                    global::LightSwitchApplication.SuscriberSearch.DetailsClass.__SuscriberSearch_InvokeSaveErrorEvent);
            private static void __SuscriberSearch_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SuscriberSearch s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SuscriberSearch_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SuscriberSearch_InvokeSavingEvent(global::LightSwitchApplication.SuscriberSearch s)
            {
                bool handled = false;
                s.SuscriberSearch_Saving(ref handled);
                return handled;
            }
            private static void __SuscriberSearch_InvokeSavedEvent(global::LightSwitchApplication.SuscriberSearch s)
            {
                s.SuscriberSearch_Saved();
            }
            private static bool __SuscriberSearch_InvokeClosingEvent(global::LightSwitchApplication.SuscriberSearch s)
            {
                bool cancel = false;
                s.SuscriberSearch_Closing(ref cancel);
                return cancel;
            }
            private static void __SuscriberSearch_InvokeCreated(global::LightSwitchApplication.SuscriberSearch s)
            {
                s.SuscriberSearch_Created();
            }
            private static void __SuscriberSearch_InvokeActivated(global::LightSwitchApplication.SuscriberSearch s)
            {
                s.SuscriberSearch_Activated();
            }
            private static bool __SuscriberSearch_InvokeSaveErrorEvent(global::LightSwitchApplication.SuscriberSearch s, global::System.Exception ex)
            {
                bool handled = false;
                s.SuscriberSearch_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SuscriberSearch.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SuscriberSearch.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable Query1Query()
            {
                return this.Screen.DataWorkspace.ApplicationData.Query1();
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Data _Query1;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::LightSwitchApplication.SubscriberItem> Query1
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::LightSwitchApplication.SubscriberItem>)base.GetItem(global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties.Query1);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Entry
                    Query1 = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Entry(
                        "Query1",
                        global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties._Query1_Stub,
                        global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties._Query1_Validate,
                        global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties._Query1_CreateQuery,
                        global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties._Query1_SelectionChanged,
                        global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties._Query1_OnCollectionChanged,
                        global::LightSwitchApplication.SuscriberSearch.DetailsClass.PropertySetProperties._Query1_OnLoaded);
                private static void _Query1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SuscriberSearch, global::LightSwitchApplication.SuscriberSearch.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Data> c, global::LightSwitchApplication.SuscriberSearch.DetailsClass d, object sf)
                {
                    c(d, ref d._Query1, sf);
                }
                private static void _Query1_Validate(global::LightSwitchApplication.SuscriberSearch s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Query1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Query1_CreateQuery(global::LightSwitchApplication.SuscriberSearch.DetailsClass d, object[] args)
                {
                    return d.Query1Query();
                }
                private static void _Query1_SelectionChanged(global::LightSwitchApplication.SuscriberSearch s)
                {
                    s.Query1_SelectionChanged();
                }
                private static void _Query1_OnCollectionChanged(global::LightSwitchApplication.SuscriberSearch s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Query1_Changed(e);
                }
                private static void _Query1_OnLoaded(global::LightSwitchApplication.SuscriberSearch s, bool succeeded)
                {
                    s.Query1_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SubscriberPhoneServiceDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SubscriberPhoneServiceDetail(int SubscriberItemId) : base("LightSwitchApplication:SubscriberPhoneServiceDetail")
        {
                this.SubscriberItemId = SubscriberItemId;
            global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SubscriberPhoneServiceDetail CreateInstance(int SubscriberItemId)
        {
            return new global::LightSwitchApplication.SubscriberPhoneServiceDetail(
                        SubscriberItemId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberPhoneServiceDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberPhoneServiceDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberPhoneServiceDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberPhoneServiceDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberPhoneServiceDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberPhoneServiceDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberPhoneServiceDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void SubscriberItem_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItem_Loaded(bool succeeded);

        partial void SubscriberItemId_Changed();

        partial void Phone_SelectionChanged();

        partial void Phone_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Loaded(bool succeeded);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.SubscriberItem SubscriberItem
        {
            get
            {
                return global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.SubscriberItem);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItem_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SubscriberItemId
        {
            get 
            {
                return global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.SubscriberItemId);
            }
            set
            {
                global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.SubscriberItemId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItemId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Phone visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.PhoneItem> Phone
        {
            get
            {
                return global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.Phone);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySet, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.CommandSet, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.SubscriberItem;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass>.Entry
                __SubscriberPhoneServiceDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.__SubscriberPhoneServiceDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.__SubscriberPhoneServiceDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.__SubscriberPhoneServiceDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.__SubscriberPhoneServiceDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.__SubscriberPhoneServiceDetail_InvokeCreated,
                    global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.__SubscriberPhoneServiceDetail_InvokeActivated,
                    global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.__SubscriberPhoneServiceDetail_InvokeSaveErrorEvent);
            private static void __SubscriberPhoneServiceDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SubscriberPhoneServiceDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SubscriberPhoneServiceDetail_InvokeSavingEvent(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
            {
                bool handled = false;
                s.SubscriberPhoneServiceDetail_Saving(ref handled);
                return handled;
            }
            private static void __SubscriberPhoneServiceDetail_InvokeSavedEvent(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
            {
                s.SubscriberPhoneServiceDetail_Saved();
            }
            private static bool __SubscriberPhoneServiceDetail_InvokeClosingEvent(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
            {
                bool cancel = false;
                s.SubscriberPhoneServiceDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __SubscriberPhoneServiceDetail_InvokeCreated(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
            {
                s.SubscriberPhoneServiceDetail_Created();
            }
            private static void __SubscriberPhoneServiceDetail_InvokeActivated(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
            {
                s.SubscriberPhoneServiceDetail_Activated();
            }
            private static bool __SubscriberPhoneServiceDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.SubscriberPhoneServiceDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PhoneQuery()
            {
                if (this.Screen.SubscriberItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PhoneItem> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PhoneItem>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.SubscriberItem.Details.Properties.Phone).Loader;
                if (loader == null)
                {
                    return null;
                }

                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    loader,
                    "ServicePlan");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Data _SubscriberItem;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, int>.Data _SubscriberItemId;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.PhoneItem>.Data _Phone;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.SubscriberItem> SubscriberItem
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.SubscriberItem>)base.GetItem(global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.SubscriberItem);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, int> SubscriberItemId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.SubscriberItemId);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.PhoneItem> Phone
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.PhoneItem>)base.GetItem(global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties.Phone);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Entry
                    SubscriberItem = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Entry(
                        "SubscriberItem",
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItem_Stub,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItem_Validate,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItem_CreateQuery,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItem_OnValueChanged,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItem_OnLoaded);
                private static void _SubscriberItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Data> c, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SubscriberItem, sf);
                }
                private static void _SubscriberItem_Validate(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.SubscriberItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _SubscriberItem_CreateQuery(global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _SubscriberItem_OnValueChanged(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
                {
                    s.SubscriberItem_Changed();
                }

                private static void _SubscriberItem_OnLoaded(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, bool succeeded)
                {
                    s.SubscriberItem_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, int>.Entry
                    SubscriberItemId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, int>.Entry(
                        "SubscriberItemId",
                        false,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItemId_Stub,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItemId_Validate,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._SubscriberItemId_OnValueChanged);
                private static void _SubscriberItemId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._SubscriberItemId, sf);
                }
                private static void _SubscriberItemId_Validate(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.SubscriberItemId_Validate(r);
                }
                private static void _SubscriberItemId_OnValueChanged(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
                {
                    s.SubscriberItemId_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.PhoneItem>.Entry
                    Phone = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.PhoneItem>.Entry(
                        "Phone",
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._Phone_Stub,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._Phone_Validate,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._Phone_CreateQuery,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._Phone_SelectionChanged,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._Phone_OnCollectionChanged,
                        global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass.PropertySetProperties._Phone_OnLoaded);
                private static void _Phone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SubscriberPhoneServiceDetail, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass, global::LightSwitchApplication.PhoneItem>.Data> c, global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Phone, sf);
                }
                private static void _Phone_Validate(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Phone_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Phone_CreateQuery(global::LightSwitchApplication.SubscriberPhoneServiceDetail.DetailsClass d, object[] args)
                {
                    return d.PhoneQuery();
                }
                private static void _Phone_SelectionChanged(global::LightSwitchApplication.SubscriberPhoneServiceDetail s)
                {
                    s.Phone_SelectionChanged();
                }
                private static void _Phone_OnCollectionChanged(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Phone_Changed(e);
                }
                private static void _Phone_OnLoaded(global::LightSwitchApplication.SubscriberPhoneServiceDetail s, bool succeeded)
                {
                    s.Phone_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
