//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "PhoneItem_SubscriberItem", "SubscriberItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.SubscriberItem), "PhoneItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.PhoneItem), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "PhoneItem_ServicePlan", "PhoneItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.PhoneItem), "ServicePlan", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ApplicationData.Implementation.ServicePlan), true)]

#endregion

namespace ApplicationData.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationDataObjectContext object using the connection string found in the 'ApplicationDataObjectContext' section of the application configuration file.
        /// </summary>
        public ApplicationDataObjectContext() : base("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(string connectionString) : base(connectionString, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(EntityConnection connection) : base(connection, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SubscriberItem> Subscriber
        {
            get
            {
                if ((_Subscriber == null))
                {
                    _Subscriber = base.CreateObjectSet<SubscriberItem>("Subscriber");
                }
                return _Subscriber;
            }
        }
        private ObjectSet<SubscriberItem> _Subscriber;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhoneItem> Phone
        {
            get
            {
                if ((_Phone == null))
                {
                    _Phone = base.CreateObjectSet<PhoneItem>("Phone");
                }
                return _Phone;
            }
        }
        private ObjectSet<PhoneItem> _Phone;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ServicePlan> ServicePlans
        {
            get
            {
                if ((_ServicePlans == null))
                {
                    _ServicePlans = base.CreateObjectSet<ServicePlan>("ServicePlans");
                }
                return _ServicePlans;
            }
        }
        private ObjectSet<ServicePlan> _ServicePlans;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subscriber EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubscriber(SubscriberItem subscriberItem)
        {
            base.AddObject("Subscriber", subscriberItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Phone EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhone(PhoneItem phoneItem)
        {
            base.AddObject("Phone", phoneItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ServicePlans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServicePlans(ServicePlan servicePlan)
        {
            base.AddObject("ServicePlans", servicePlan);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="PhoneItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhoneItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhoneItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        /// <param name="mDN">Initial value of the MDN property.</param>
        /// <param name="mSID">Initial value of the MSID property.</param>
        /// <param name="mEID">Initial value of the MEID property.</param>
        /// <param name="eSN">Initial value of the ESN property.</param>
        /// <param name="mSL">Initial value of the MSL property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="phoneItem_SubscriberItem">Initial value of the PhoneItem_SubscriberItem property.</param>
        public static PhoneItem CreatePhoneItem(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.String mDN, global::System.String mSID, global::System.String mEID, global::System.String eSN, global::System.String mSL, global::System.Boolean active, global::System.Int32 phoneItem_SubscriberItem)
        {
            PhoneItem phoneItem = new PhoneItem();
            phoneItem.Id = id;
            phoneItem.RowVersion = rowVersion;
            phoneItem.MDN = mDN;
            phoneItem.MSID = mSID;
            phoneItem.MEID = mEID;
            phoneItem.ESN = eSN;
            phoneItem.MSL = mSL;
            phoneItem.Active = active;
            phoneItem.PhoneItem_SubscriberItem = phoneItem_SubscriberItem;
            return phoneItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MDN
        {
            get
            {
                return _MDN;
            }
            set
            {
                OnMDNChanging(value);
                ReportPropertyChanging("MDN");
                _MDN = value;
                ReportPropertyChanged("MDN");
                OnMDNChanged();
            }
        }
        private global::System.String _MDN;
        partial void OnMDNChanging(global::System.String value);
        partial void OnMDNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MSID
        {
            get
            {
                return _MSID;
            }
            set
            {
                OnMSIDChanging(value);
                ReportPropertyChanging("MSID");
                _MSID = value;
                ReportPropertyChanged("MSID");
                OnMSIDChanged();
            }
        }
        private global::System.String _MSID;
        partial void OnMSIDChanging(global::System.String value);
        partial void OnMSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MEID
        {
            get
            {
                return _MEID;
            }
            set
            {
                OnMEIDChanging(value);
                ReportPropertyChanging("MEID");
                _MEID = value;
                ReportPropertyChanged("MEID");
                OnMEIDChanged();
            }
        }
        private global::System.String _MEID;
        partial void OnMEIDChanging(global::System.String value);
        partial void OnMEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESN
        {
            get
            {
                return _ESN;
            }
            set
            {
                OnESNChanging(value);
                ReportPropertyChanging("ESN");
                _ESN = value;
                ReportPropertyChanged("ESN");
                OnESNChanged();
            }
        }
        private global::System.String _ESN;
        partial void OnESNChanging(global::System.String value);
        partial void OnESNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MSL
        {
            get
            {
                return _MSL;
            }
            set
            {
                OnMSLChanging(value);
                ReportPropertyChanging("MSL");
                _MSL = value;
                ReportPropertyChanged("MSL");
                OnMSLChanged();
            }
        }
        private global::System.String _MSL;
        partial void OnMSLChanging(global::System.String value);
        partial void OnMSLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = value;
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeviceType
        {
            get
            {
                return _DeviceType;
            }
            set
            {
                OnDeviceTypeChanging(value);
                ReportPropertyChanging("DeviceType");
                _DeviceType = value;
                ReportPropertyChanged("DeviceType");
                OnDeviceTypeChanged();
            }
        }
        private global::System.String _DeviceType;
        partial void OnDeviceTypeChanging(global::System.String value);
        partial void OnDeviceTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = value;
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = value;
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType
        {
            get
            {
                return _PhoneType;
            }
            set
            {
                OnPhoneTypeChanging(value);
                ReportPropertyChanging("PhoneType");
                _PhoneType = value;
                ReportPropertyChanged("PhoneType");
                OnPhoneTypeChanged();
            }
        }
        private global::System.String _PhoneType;
        partial void OnPhoneTypeChanging(global::System.String value);
        partial void OnPhoneTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhoneItem_SubscriberItem
        {
            get
            {
                return _PhoneItem_SubscriberItem;
            }
            set
            {
                OnPhoneItem_SubscriberItemChanging(value);
                ReportPropertyChanging("PhoneItem_SubscriberItem");
                _PhoneItem_SubscriberItem = value;
                ReportPropertyChanged("PhoneItem_SubscriberItem");
                OnPhoneItem_SubscriberItemChanged();
            }
        }
        private global::System.Int32 _PhoneItem_SubscriberItem;
        partial void OnPhoneItem_SubscriberItemChanging(global::System.Int32 value);
        partial void OnPhoneItem_SubscriberItemChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "PhoneItem_SubscriberItem", "SubscriberItem")]
        public SubscriberItem SubscriberItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubscriberItem>("LightSwitchApplication.PhoneItem_SubscriberItem", "SubscriberItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubscriberItem>("LightSwitchApplication.PhoneItem_SubscriberItem", "SubscriberItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SubscriberItem> SubscriberItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubscriberItem>("LightSwitchApplication.PhoneItem_SubscriberItem", "SubscriberItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SubscriberItem>("LightSwitchApplication.PhoneItem_SubscriberItem", "SubscriberItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "PhoneItem_ServicePlan", "ServicePlan")]
        public ServicePlan ServicePlan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ServicePlan>("LightSwitchApplication.PhoneItem_ServicePlan", "ServicePlan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ServicePlan>("LightSwitchApplication.PhoneItem_ServicePlan", "ServicePlan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ServicePlan> ServicePlanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ServicePlan>("LightSwitchApplication.PhoneItem_ServicePlan", "ServicePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ServicePlan>("LightSwitchApplication.PhoneItem_ServicePlan", "ServicePlan", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="ServicePlan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ServicePlan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ServicePlan object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        /// <param name="internationalDialing">Initial value of the InternationalDialing property.</param>
        /// <param name="voicePlan">Initial value of the VoicePlan property.</param>
        /// <param name="dataPlan">Initial value of the DataPlan property.</param>
        /// <param name="hotSpot">Initial value of the HotSpot property.</param>
        public static ServicePlan CreateServicePlan(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.Boolean internationalDialing, global::System.String voicePlan, global::System.String dataPlan, global::System.Boolean hotSpot)
        {
            ServicePlan servicePlan = new ServicePlan();
            servicePlan.Id = id;
            servicePlan.RowVersion = rowVersion;
            servicePlan.InternationalDialing = internationalDialing;
            servicePlan.VoicePlan = voicePlan;
            servicePlan.DataPlan = dataPlan;
            servicePlan.HotSpot = hotSpot;
            return servicePlan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean InternationalDialing
        {
            get
            {
                return _InternationalDialing;
            }
            set
            {
                OnInternationalDialingChanging(value);
                ReportPropertyChanging("InternationalDialing");
                _InternationalDialing = value;
                ReportPropertyChanged("InternationalDialing");
                OnInternationalDialingChanged();
            }
        }
        private global::System.Boolean _InternationalDialing;
        partial void OnInternationalDialingChanging(global::System.Boolean value);
        partial void OnInternationalDialingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VoicePlan
        {
            get
            {
                return _VoicePlan;
            }
            set
            {
                OnVoicePlanChanging(value);
                ReportPropertyChanging("VoicePlan");
                _VoicePlan = value;
                ReportPropertyChanged("VoicePlan");
                OnVoicePlanChanged();
            }
        }
        private global::System.String _VoicePlan;
        partial void OnVoicePlanChanging(global::System.String value);
        partial void OnVoicePlanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataPlan
        {
            get
            {
                return _DataPlan;
            }
            set
            {
                OnDataPlanChanging(value);
                ReportPropertyChanging("DataPlan");
                _DataPlan = value;
                ReportPropertyChanged("DataPlan");
                OnDataPlanChanged();
            }
        }
        private global::System.String _DataPlan;
        partial void OnDataPlanChanging(global::System.String value);
        partial void OnDataPlanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HotSpot
        {
            get
            {
                return _HotSpot;
            }
            set
            {
                OnHotSpotChanging(value);
                ReportPropertyChanging("HotSpot");
                _HotSpot = value;
                ReportPropertyChanged("HotSpot");
                OnHotSpotChanged();
            }
        }
        private global::System.Boolean _HotSpot;
        partial void OnHotSpotChanging(global::System.Boolean value);
        partial void OnHotSpotChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "PhoneItem_ServicePlan", "PhoneItem")]
        public PhoneItem PhoneItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneItem>("LightSwitchApplication.PhoneItem_ServicePlan", "PhoneItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneItem>("LightSwitchApplication.PhoneItem_ServicePlan", "PhoneItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhoneItem> PhoneItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneItem>("LightSwitchApplication.PhoneItem_ServicePlan", "PhoneItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhoneItem>("LightSwitchApplication.PhoneItem_ServicePlan", "PhoneItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="SubscriberItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubscriberItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SubscriberItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static SubscriberItem CreateSubscriberItem(global::System.Int32 id, global::System.Byte[] rowVersion, global::System.String firstName, global::System.String lastName)
        {
            SubscriberItem subscriberItem = new SubscriberItem();
            subscriberItem.Id = id;
            subscriberItem.RowVersion = rowVersion;
            subscriberItem.FirstName = firstName;
            subscriberItem.LastName = lastName;
            return subscriberItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = value;
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = value;
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = value;
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                OnGroupIdChanging(value);
                ReportPropertyChanging("GroupId");
                _GroupId = value;
                ReportPropertyChanged("GroupId");
                OnGroupIdChanged();
            }
        }
        private global::System.String _GroupId;
        partial void OnGroupIdChanging(global::System.String value);
        partial void OnGroupIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "PhoneItem_SubscriberItem", "PhoneItem")]
        public EntityCollection<PhoneItem> Phone
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhoneItem>("LightSwitchApplication.PhoneItem_SubscriberItem", "PhoneItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhoneItem>("LightSwitchApplication.PhoneItem_SubscriberItem", "PhoneItem", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
