//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Inserting(global::LightSwitchApplication.SubscriberItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Inserted(global::LightSwitchApplication.SubscriberItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Updating(global::LightSwitchApplication.SubscriberItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Updated(global::LightSwitchApplication.SubscriberItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Deleting(global::LightSwitchApplication.SubscriberItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Deleted(global::LightSwitchApplication.SubscriberItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Validate(global::LightSwitchApplication.SubscriberItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subscriber_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SubscriberItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Inserting(global::LightSwitchApplication.PhoneItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Inserted(global::LightSwitchApplication.PhoneItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Updating(global::LightSwitchApplication.PhoneItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Updated(global::LightSwitchApplication.PhoneItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Deleting(global::LightSwitchApplication.PhoneItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Deleted(global::LightSwitchApplication.PhoneItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Validate(global::LightSwitchApplication.PhoneItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PhoneItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Inserting(global::LightSwitchApplication.ServicePlan entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Inserted(global::LightSwitchApplication.ServicePlan entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Updating(global::LightSwitchApplication.ServicePlan entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Updated(global::LightSwitchApplication.ServicePlan entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Deleting(global::LightSwitchApplication.ServicePlan entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Deleted(global::LightSwitchApplication.ServicePlan entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Validate(global::LightSwitchApplication.ServicePlan entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlans_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ServicePlan, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query1_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void Query1_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query1_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.SubscriberItem> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void Query1_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.SubscriberItem> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void Query1_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.SubscriberItem>
                __SubscriberEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.SubscriberItem>(
                    "Subscriber",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Subscriber_Filter);
            private static bool __Subscriber_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Subscriber_CanInsert(ref result);
                return result;
            }
            private static bool __Subscriber_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Subscriber_CanUpdate(ref result);
                return result;
            }
            private static bool __Subscriber_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Subscriber_CanDelete(ref result);
                return result;
            }
            private static bool __Subscriber_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Subscriber_CanRead(ref result);
                return result;
            }
            private static void __Subscriber_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SubscriberItem e)
            {
                d.Subscriber_Inserting(e);
            }
            private static void __Subscriber_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SubscriberItem e)
            {
                d.Subscriber_Inserted(e);
            }
            private static void __Subscriber_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SubscriberItem e)
            {
                d.Subscriber_Updating(e);
            }
            private static void __Subscriber_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SubscriberItem e)
            {
                d.Subscriber_Updated(e);
            }
            private static void __Subscriber_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SubscriberItem e)
            {
                d.Subscriber_Deleting(e);
            }
            private static void __Subscriber_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SubscriberItem e)
            {
                d.Subscriber_Deleted(e);
            }
            private static void __Subscriber_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.SubscriberItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Subscriber_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SubscriberItem, bool>> __Subscriber_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SubscriberItem, bool>> filter = null;
                d.Subscriber_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.PhoneItem>
                __PhoneEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.PhoneItem>(
                    "Phone",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Phone_Filter);
            private static bool __Phone_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Phone_CanInsert(ref result);
                return result;
            }
            private static bool __Phone_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Phone_CanUpdate(ref result);
                return result;
            }
            private static bool __Phone_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Phone_CanDelete(ref result);
                return result;
            }
            private static bool __Phone_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Phone_CanRead(ref result);
                return result;
            }
            private static void __Phone_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PhoneItem e)
            {
                d.Phone_Inserting(e);
            }
            private static void __Phone_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PhoneItem e)
            {
                d.Phone_Inserted(e);
            }
            private static void __Phone_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PhoneItem e)
            {
                d.Phone_Updating(e);
            }
            private static void __Phone_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PhoneItem e)
            {
                d.Phone_Updated(e);
            }
            private static void __Phone_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PhoneItem e)
            {
                d.Phone_Deleting(e);
            }
            private static void __Phone_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PhoneItem e)
            {
                d.Phone_Deleted(e);
            }
            private static void __Phone_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Phone_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PhoneItem, bool>> __Phone_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PhoneItem, bool>> filter = null;
                d.Phone_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.ServicePlan>
                __ServicePlansEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.ServicePlan>(
                    "ServicePlans",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ServicePlans_Filter);
            private static bool __ServicePlans_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ServicePlans_CanInsert(ref result);
                return result;
            }
            private static bool __ServicePlans_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ServicePlans_CanUpdate(ref result);
                return result;
            }
            private static bool __ServicePlans_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ServicePlans_CanDelete(ref result);
                return result;
            }
            private static bool __ServicePlans_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ServicePlans_CanRead(ref result);
                return result;
            }
            private static void __ServicePlans_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ServicePlan e)
            {
                d.ServicePlans_Inserting(e);
            }
            private static void __ServicePlans_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ServicePlan e)
            {
                d.ServicePlans_Inserted(e);
            }
            private static void __ServicePlans_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ServicePlan e)
            {
                d.ServicePlans_Updating(e);
            }
            private static void __ServicePlans_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ServicePlan e)
            {
                d.ServicePlans_Updated(e);
            }
            private static void __ServicePlans_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ServicePlan e)
            {
                d.ServicePlans_Deleting(e);
            }
            private static void __ServicePlans_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ServicePlan e)
            {
                d.ServicePlans_Deleted(e);
            }
            private static void __ServicePlans_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ServicePlan e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.ServicePlans_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ServicePlan, bool>> __ServicePlans_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ServicePlan, bool>> filter = null;
                d.ServicePlans_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.SubscriberItem>
                __Query1Entry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.SubscriberItem>(
                    "Query1",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query1_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query1_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query1_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query1_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query1_PreprocessQuery);
            private static bool __Query1_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.Query1_CanExecute(ref r);
                return r;
            }
            private static void __Query1_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Query1_Executing();
            }
            private static void __Query1_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Query1_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.SubscriberItem>)args[0]);
            }
            private static void __Query1_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.Query1_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __Query1_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.SubscriberItem> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.SubscriberItem>)args[0];
                d.Query1_PreprocessQuery(ref query);
                return query;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    #endregion
}
