

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SubscriberItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the SubscriberItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SubscriberItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SubscriberItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SubscriberItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.SubscriberItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.SubscriberItem.DetailsClass.SetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.SubscriberItem.DetailsClass.SetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirstName
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.FirstName);
            }
            set
            {
                global::LightSwitchApplication.SubscriberItem.DetailsClass.SetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.FirstName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastName
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.LastName);
            }
            set
            {
                global::LightSwitchApplication.SubscriberItem.DetailsClass.SetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.LastName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Comment
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Comment);
            }
            set
            {
                global::LightSwitchApplication.SubscriberItem.DetailsClass.SetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Comment, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string GroupId
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.GroupId);
            }
            set
            {
                global::LightSwitchApplication.SubscriberItem.DetailsClass.SetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.GroupId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GroupId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GroupId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GroupId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PhoneItem> Phone
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetValue(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Phone);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PhoneItem> PhoneQuery
        {
            get
            {
                return global::LightSwitchApplication.SubscriberItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Phone);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.SubscriberItem,
                global::LightSwitchApplication.SubscriberItem.DetailsClass,
                global::LightSwitchApplication.SubscriberItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass>.Entry
                __SubscriberItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.SubscriberItem.DetailsClass.__SubscriberItem_CreateNew,
                    global::LightSwitchApplication.SubscriberItem.DetailsClass.__SubscriberItem_Created,
                    global::LightSwitchApplication.SubscriberItem.DetailsClass.__SubscriberItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.SubscriberItem __SubscriberItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SubscriberItem> es)
            {
                return new global::LightSwitchApplication.SubscriberItem(es);
            }
            private static void __SubscriberItem_Created(global::LightSwitchApplication.SubscriberItem e)
            {
                e.SubscriberItem_Created();
            }
            private static bool __SubscriberItem_AllowSaveWithErrors(global::LightSwitchApplication.SubscriberItem e)
            {
                bool result = false;
                e.SubscriberItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string> FirstName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.FirstName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string> LastName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.LastName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string> Comment
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Comment) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string> GroupId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.GroupId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, global::LightSwitchApplication.PhoneItem> Phone
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Phone) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, global::LightSwitchApplication.PhoneItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string FirstName { get; set; }
                new string LastName { get; set; }
                new string Comment { get; set; }
                new string GroupId { get; set; }
                new global::System.Collections.IEnumerable Phone { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.SubscriberItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.SubscriberItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.SubscriberItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.SubscriberItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.SubscriberItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.SubscriberItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.SubscriberItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.SubscriberItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry
                    FirstName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry(
                        "FirstName",
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._FirstName_Stub,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._FirstName_ComputeIsReadOnly,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._FirstName_Validate,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._FirstName_GetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._FirstName_SetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._FirstName_OnValueChanged);
                private static void _FirstName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.SubscriberItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FirstName, sf);
                }
                private static bool _FirstName_ComputeIsReadOnly(global::LightSwitchApplication.SubscriberItem e)
                {
                    bool result = false;
                    e.FirstName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirstName_Validate(global::LightSwitchApplication.SubscriberItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirstName_Validate(r);
                }
                private static string _FirstName_GetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FirstName;
                }
                private static void _FirstName_SetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirstName = v;
                }
                private static void _FirstName_OnValueChanged(global::LightSwitchApplication.SubscriberItem e)
                {
                    e.FirstName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry
                    LastName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry(
                        "LastName",
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._LastName_Stub,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._LastName_ComputeIsReadOnly,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._LastName_Validate,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._LastName_GetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._LastName_SetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._LastName_OnValueChanged);
                private static void _LastName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.SubscriberItem.DetailsClass d, object sf)
                {
                    c(d, ref d._LastName, sf);
                }
                private static bool _LastName_ComputeIsReadOnly(global::LightSwitchApplication.SubscriberItem e)
                {
                    bool result = false;
                    e.LastName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LastName_Validate(global::LightSwitchApplication.SubscriberItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LastName_Validate(r);
                }
                private static string _LastName_GetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.ImplementationEntity.LastName;
                }
                private static void _LastName_SetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LastName = v;
                }
                private static void _LastName_OnValueChanged(global::LightSwitchApplication.SubscriberItem e)
                {
                    e.LastName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry
                    Comment = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry(
                        "Comment",
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Comment_Stub,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Comment_ComputeIsReadOnly,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Comment_Validate,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Comment_GetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Comment_SetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Comment_OnValueChanged);
                private static void _Comment_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.SubscriberItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Comment, sf);
                }
                private static bool _Comment_ComputeIsReadOnly(global::LightSwitchApplication.SubscriberItem e)
                {
                    bool result = false;
                    e.Comment_IsReadOnly(ref result);
                    return result;
                }
                private static void _Comment_Validate(global::LightSwitchApplication.SubscriberItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Comment_Validate(r);
                }
                private static string _Comment_GetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Comment;
                }
                private static void _Comment_SetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Comment = v;
                }
                private static void _Comment_OnValueChanged(global::LightSwitchApplication.SubscriberItem e)
                {
                    e.Comment_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry
                    GroupId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Entry(
                        "GroupId",
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._GroupId_Stub,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._GroupId_ComputeIsReadOnly,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._GroupId_Validate,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._GroupId_GetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._GroupId_SetImplementationValue,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._GroupId_OnValueChanged);
                private static void _GroupId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.SubscriberItem.DetailsClass d, object sf)
                {
                    c(d, ref d._GroupId, sf);
                }
                private static bool _GroupId_ComputeIsReadOnly(global::LightSwitchApplication.SubscriberItem e)
                {
                    bool result = false;
                    e.GroupId_IsReadOnly(ref result);
                    return result;
                }
                private static void _GroupId_Validate(global::LightSwitchApplication.SubscriberItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.GroupId_Validate(r);
                }
                private static string _GroupId_GetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.ImplementationEntity.GroupId;
                }
                private static void _GroupId_SetImplementationValue(global::LightSwitchApplication.SubscriberItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.GroupId = v;
                }
                private static void _GroupId_OnValueChanged(global::LightSwitchApplication.SubscriberItem e)
                {
                    e.GroupId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, global::LightSwitchApplication.PhoneItem>.Entry
                    Phone = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, global::LightSwitchApplication.PhoneItem>.Entry(
                        "Phone",
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Phone_Stub,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Phone_GetReferencedEntities,
                        global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties._Phone_GetEntityCollection);
                private static void _Phone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SubscriberItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, global::LightSwitchApplication.PhoneItem>.Data> c, global::LightSwitchApplication.SubscriberItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Phone, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PhoneItem> _Phone_GetReferencedEntities(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass>(global::LightSwitchApplication.SubscriberItem.DetailsClass.PropertySetProperties.Phone, ref d._Phone);
                }
                private static global::System.Collections.IEnumerable _Phone_GetEntityCollection(global::LightSwitchApplication.SubscriberItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Phone;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data _FirstName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data _LastName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data _Comment;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, string>.Data _GroupId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass, global::LightSwitchApplication.PhoneItem>.Data _Phone;
            
        }
    
        #endregion
    }
    
    #endregion
}
