

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class PhoneItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PhoneItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PhoneItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PhoneItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PhoneItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PhoneItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MDN
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MDN);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MDN, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MDN_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MDN_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MDN_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MSID
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MSID);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MSID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MSID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MSID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MSID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MEID
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MEID);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MEID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MEID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MEID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MEID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ESN
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ESN);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ESN, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ESN_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ESN_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ESN_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MSL
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MSL);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MSL, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MSL_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MSL_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MSL_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Active
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Active);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Active, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DeviceType
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.DeviceType);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.DeviceType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeviceType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Manufacturer
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Manufacturer);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Manufacturer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Manufacturer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Manufacturer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Manufacturer_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Comment
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Comment);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Comment, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PhoneType
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.PhoneType);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.PhoneType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhoneType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.SubscriberItem SubscriberItem
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.SubscriberItem);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.SubscriberItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubscriberItem_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ServicePlan ServicePlan
        {
            get
            {
                return global::LightSwitchApplication.PhoneItem.DetailsClass.GetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ServicePlan);
            }
            set
            {
                global::LightSwitchApplication.PhoneItem.DetailsClass.SetValue(this, global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ServicePlan, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlan_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlan_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServicePlan_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PhoneItem,
                global::LightSwitchApplication.PhoneItem.DetailsClass,
                global::LightSwitchApplication.PhoneItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass>.Entry
                __PhoneItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.PhoneItem.DetailsClass.__PhoneItem_CreateNew,
                    global::LightSwitchApplication.PhoneItem.DetailsClass.__PhoneItem_Created,
                    global::LightSwitchApplication.PhoneItem.DetailsClass.__PhoneItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PhoneItem __PhoneItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PhoneItem> es)
            {
                return new global::LightSwitchApplication.PhoneItem(es);
            }
            private static void __PhoneItem_Created(global::LightSwitchApplication.PhoneItem e)
            {
                e.PhoneItem_Created();
            }
            private static bool __PhoneItem_AllowSaveWithErrors(global::LightSwitchApplication.PhoneItem e)
            {
                bool result = false;
                e.PhoneItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> MDN
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MDN) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> MSID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MSID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> MEID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MEID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> ESN
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ESN) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> MSL
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.MSL) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, bool> Active
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Active) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> DeviceType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.DeviceType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> Manufacturer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Manufacturer) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> Comment
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.Comment) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string> PhoneType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.PhoneType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.SubscriberItem> SubscriberItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.SubscriberItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.SubscriberItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.ServicePlan> ServicePlan
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ServicePlan) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.ServicePlan>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string MDN { get; set; }
                new string MSID { get; set; }
                new string MEID { get; set; }
                new string ESN { get; set; }
                new string MSL { get; set; }
                new bool Active { get; set; }
                new string DeviceType { get; set; }
                new string Manufacturer { get; set; }
                new string Comment { get; set; }
                new string PhoneType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation SubscriberItem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ServicePlan { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    MDN = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "MDN",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MDN_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MDN_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MDN_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MDN_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MDN_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MDN_OnValueChanged);
                private static void _MDN_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MDN, sf);
                }
                private static bool _MDN_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.MDN_IsReadOnly(ref result);
                    return result;
                }
                private static void _MDN_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MDN_Validate(r);
                }
                private static string _MDN_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MDN;
                }
                private static void _MDN_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MDN = v;
                }
                private static void _MDN_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.MDN_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    MSID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "MSID",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSID_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSID_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSID_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSID_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSID_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSID_OnValueChanged);
                private static void _MSID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MSID, sf);
                }
                private static bool _MSID_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.MSID_IsReadOnly(ref result);
                    return result;
                }
                private static void _MSID_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MSID_Validate(r);
                }
                private static string _MSID_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MSID;
                }
                private static void _MSID_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MSID = v;
                }
                private static void _MSID_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.MSID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    MEID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "MEID",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MEID_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MEID_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MEID_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MEID_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MEID_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MEID_OnValueChanged);
                private static void _MEID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MEID, sf);
                }
                private static bool _MEID_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.MEID_IsReadOnly(ref result);
                    return result;
                }
                private static void _MEID_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MEID_Validate(r);
                }
                private static string _MEID_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MEID;
                }
                private static void _MEID_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MEID = v;
                }
                private static void _MEID_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.MEID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    ESN = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "ESN",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ESN_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ESN_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ESN_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ESN_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ESN_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ESN_OnValueChanged);
                private static void _ESN_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ESN, sf);
                }
                private static bool _ESN_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.ESN_IsReadOnly(ref result);
                    return result;
                }
                private static void _ESN_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ESN_Validate(r);
                }
                private static string _ESN_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ESN;
                }
                private static void _ESN_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ESN = v;
                }
                private static void _ESN_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.ESN_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    MSL = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "MSL",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSL_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSL_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSL_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSL_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSL_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._MSL_OnValueChanged);
                private static void _MSL_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MSL, sf);
                }
                private static bool _MSL_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.MSL_IsReadOnly(ref result);
                    return result;
                }
                private static void _MSL_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MSL_Validate(r);
                }
                private static string _MSL_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MSL;
                }
                private static void _MSL_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MSL = v;
                }
                private static void _MSL_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.MSL_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, bool>.Entry
                    Active = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, bool>.Entry(
                        "Active",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Active_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Active_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Active_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Active_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Active_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Active_OnValueChanged);
                private static void _Active_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Active, sf);
                }
                private static bool _Active_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.Active_IsReadOnly(ref result);
                    return result;
                }
                private static void _Active_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Active_Validate(r);
                }
                private static bool _Active_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Active;
                }
                private static void _Active_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Active = v;
                }
                private static void _Active_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.Active_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    DeviceType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "DeviceType",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._DeviceType_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._DeviceType_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._DeviceType_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._DeviceType_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._DeviceType_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._DeviceType_OnValueChanged);
                private static void _DeviceType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._DeviceType, sf);
                }
                private static bool _DeviceType_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.DeviceType_IsReadOnly(ref result);
                    return result;
                }
                private static void _DeviceType_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DeviceType_Validate(r);
                }
                private static string _DeviceType_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.DeviceType;
                }
                private static void _DeviceType_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DeviceType = v;
                }
                private static void _DeviceType_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.DeviceType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    Manufacturer = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "Manufacturer",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Manufacturer_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Manufacturer_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Manufacturer_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Manufacturer_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Manufacturer_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Manufacturer_OnValueChanged);
                private static void _Manufacturer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Manufacturer, sf);
                }
                private static bool _Manufacturer_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.Manufacturer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Manufacturer_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Manufacturer_Validate(r);
                }
                private static string _Manufacturer_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Manufacturer;
                }
                private static void _Manufacturer_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Manufacturer = v;
                }
                private static void _Manufacturer_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.Manufacturer_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    Comment = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "Comment",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Comment_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Comment_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Comment_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Comment_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Comment_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._Comment_OnValueChanged);
                private static void _Comment_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Comment, sf);
                }
                private static bool _Comment_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.Comment_IsReadOnly(ref result);
                    return result;
                }
                private static void _Comment_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Comment_Validate(r);
                }
                private static string _Comment_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Comment;
                }
                private static void _Comment_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Comment = v;
                }
                private static void _Comment_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.Comment_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry
                    PhoneType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Entry(
                        "PhoneType",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._PhoneType_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._PhoneType_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._PhoneType_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._PhoneType_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._PhoneType_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._PhoneType_OnValueChanged);
                private static void _PhoneType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PhoneType, sf);
                }
                private static bool _PhoneType_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.PhoneType_IsReadOnly(ref result);
                    return result;
                }
                private static void _PhoneType_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PhoneType_Validate(r);
                }
                private static string _PhoneType_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PhoneType;
                }
                private static void _PhoneType_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PhoneType = v;
                }
                private static void _PhoneType_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.PhoneType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Entry
                    SubscriberItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Entry(
                        "SubscriberItem",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_Refresh,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._SubscriberItem_OnValueChanged);
                private static void _SubscriberItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._SubscriberItem, sf);
                }
                private static bool _SubscriberItem_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.SubscriberItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _SubscriberItem_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SubscriberItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _SubscriberItem_GetCoreImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.SubscriberItem;
                }
                private static global::LightSwitchApplication.SubscriberItem _SubscriberItem_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.SubscriberItem, global::LightSwitchApplication.SubscriberItem.DetailsClass>(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.SubscriberItem, ref d._SubscriberItem);
                }
                private static void _SubscriberItem_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, global::LightSwitchApplication.SubscriberItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.SubscriberItem, ref d._SubscriberItem, (i, ev) => i.SubscriberItem = ev, v);
                }
                private static void _SubscriberItem_Refresh(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.SubscriberItem, ref d._SubscriberItem);
                }
                private static void _SubscriberItem_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.SubscriberItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.ServicePlan>.Entry
                    ServicePlan = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.ServicePlan>.Entry(
                        "ServicePlan",
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_Stub,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_ComputeIsReadOnly,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_Validate,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_GetCoreImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_GetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_SetImplementationValue,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_Refresh,
                        global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties._ServicePlan_OnValueChanged);
                private static void _ServicePlan_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PhoneItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.ServicePlan>.Data> c, global::LightSwitchApplication.PhoneItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ServicePlan, sf);
                }
                private static bool _ServicePlan_ComputeIsReadOnly(global::LightSwitchApplication.PhoneItem e)
                {
                    bool result = false;
                    e.ServicePlan_IsReadOnly(ref result);
                    return result;
                }
                private static void _ServicePlan_Validate(global::LightSwitchApplication.PhoneItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ServicePlan_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ServicePlan_GetCoreImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ServicePlan;
                }
                private static global::LightSwitchApplication.ServicePlan _ServicePlan_GetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ServicePlan, global::LightSwitchApplication.ServicePlan.DetailsClass>(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ServicePlan, ref d._ServicePlan);
                }
                private static void _ServicePlan_SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass d, global::LightSwitchApplication.ServicePlan v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ServicePlan, ref d._ServicePlan, (i, ev) => i.ServicePlan = ev, v);
                }
                private static void _ServicePlan_Refresh(global::LightSwitchApplication.PhoneItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PhoneItem.DetailsClass.PropertySetProperties.ServicePlan, ref d._ServicePlan);
                }
                private static void _ServicePlan_OnValueChanged(global::LightSwitchApplication.PhoneItem e)
                {
                    e.ServicePlan_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _MDN;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _MSID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _MEID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _ESN;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _MSL;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, bool>.Data _Active;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _DeviceType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _Manufacturer;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _Comment;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, string>.Data _PhoneType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.SubscriberItem>.Data _SubscriberItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PhoneItem, global::LightSwitchApplication.PhoneItem.DetailsClass, global::LightSwitchApplication.ServicePlan>.Data _ServicePlan;
            
        }
    
        #endregion
    }
    
    #endregion
}
